### ISSUE TITLE
Una pregunta

### ISSUE THREAD

**Issue by faquino** [josemmo/movistartv#1]
Entonces, ¿se trata de una solución '*todo en uno*'? ¿No sería necesario UDP proxy ni grabber EPG? Hace algún tiempo probé con el [XMLTV Grabber](https://github.com/MovistarTV/tv_grab_es_movistartv) en una Raspberry Pi, junto con [udpxy](https://github.com/pcherenkov/udpxy) en un Edgerouter ER-X y [TVirl](https://github.com/stari4ek/tvirl)... funcionaba, pero en conjunto era un incordio de mantener.
¿Algún foro/hilo para seguir el progreso de la app, videos, wiki etc?
Un saludo y gran trabajo, me quito el sombrero

**Comment by josemmo** [comment]
Hola @faquino,

Muchas gracias! :)

Sí, es todo en uno, como si fuera el propio decodificador de Movistar.
Hay [un tema](https://www.adslzone.net/foro/movistar-tv-imagenio.38/canales-programacion-movistar-android-tv.477246/) en ADSLZone, aunque el desarrollo del proyecto lo tengo un poco abandonado.
