### ISSUE TITLE
Instalación beta Movistar en Fire tv Amazon 4K 

### ISSUE THREAD

**Issue by victormanrc** [josemmo/movistartv#3]
Muy buenas Josemmo,

he estad instalando tu beta (la penúltima porque la última me decís que no era compatible) con el downloader addon en mi fire tv stick 4K de Amazon.

- tengo contratado Movistar con fútbol pero estoy fuera de casa ( por eso quería probar esta beta en mi tv fuera de casa)
- Tengo instalada la app tv oficial 
Pregunta:

he instalado la beta (penúltima) pero no entiendo cuando dices “ tienes que sintonizar la fuente de canales que crea después de instalar la app”

Tampoco me aparece la app beta en mi catálogo de apps, solo la oficial .

¿que pasos me están faltando?

Gracias

**Comment by josemmo** [comment]
Hola @victormanrc,

El Amazon Fire TV tiene Android pero no Android TV (son sistemas operativos diferentes), imagino que por eso te aparece el mensaje de que no es compatible.

Aun así, esta app no funciona fuera de casa, necesitas estar conectado al router que te proporciona Movistar.
